name: Comment

on:
  issues:
    types: [opened, labeled, assigned, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/feature_request.md
        id: create-issue
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Please see new issue ${{ steps.create-issue.outputs.url }}  
            Please see actions log ${{ jobs.html_url }}  
            
