name: Assign issues to project

on:
  issues:
    types: [opened, labeled, assigned, reopened]
  pull_request:
    types: [opened]
  issue_comment:
    tyoes: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: srggrs/assign-one-project-github-action@1.2.0
        with:
          project: 'https://github.com/yurake/dockerfile/projects/1'
