name: e2e test on Minikube

on:
  push:
  pull_request:

jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: delete not use modules
        run: |
          df -h /
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /opt/hostedtoolcache/Python
          sudo rm -rf /opt/hostedtoolcache/Ruby
          df -h /
      - name: manage disk
        run: |
          echo ${PATH}
          sudo du -ma / | sort -rn | head -100
          sudo du -m / | sort -rn | head -100
