name: e2e test on Minikube

on:
  push:
  pull_request:

jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: manage disk
        run: |
          sudo du -ma / | sort -rn | head -100
          sudo du -m / | sort -rn | head -100
