name: e2e test on Minikube

on:
  push:
  pull_request:

jobs:
  minikube:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        minikube: [v1.8.2, v1.9.2]
        kubernetes: [v1.18.0, v1.18.2]
    steps:
      - name: delete installed software not use
        run: |
          df -h /
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /opt/hostedtoolcache/Python
          sudo rm -rf /opt/hostedtoolcache/Ruby
          df -h /
          
      - name: checkout
        uses: actions/checkout@v1
      - name: setup minikube
        uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: ${{ matrix.minikube }}
          kubernetes version: ${{ matrix.kubernetes }}
      - name: minikube addon settings
        run: |
          sudo which kubectl
          sudo ls -la /home/runner/work/_temp
          sudo mv /home/runner/work/_temp/.minikube $HOME/.
          sudo chown -R $USER $HOME/.minikube
          sudo pwd
          sudo ls -la $HOME
          sudo $HOME/minikube addons enable ingress
          sudo $HOME/minikube addons list
          sudo minikube addons list
