name: e2e test on Minikube

on:
  push:
  pull_request:

jobs:
  minikube:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        minikube: [v1.8.2, v1.9.2]
        kubernetes: [v1.18.0, v1.18.2]
    steps:
      - name: checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/yurake/k8s-3tier-webapp
      - name: setup minikube
        uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: ${{ matrix.minikube }}
          kubernetes version: ${{ matrix.kubernetes }}
      - name: minikube addon settings
        run: |
          sudo mv /home/runner/work/_temp/.minikube $HOME
          sudo mv /home/runner/work/_temp/minikube /usr/bin
          sudo minikube addons enable ingress
          sudo minikube addons list
          sudo echo ::set-env name=MINIKUBE_HOME::$HOME
          sudo cat $HOME/.kube/config
      - name: apply minimal service
        run: |
          sudo sh ./k8s-3tier-webapp/kubernetes/apply-default-minimal.sh
