name: e2e test on Minikube

on:
  push:
  pull_request:

jobs:
  minikube:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        minikube: [v1.8.2, v1.9.2]
        kubernetes: [v1.18.0, v1.18.2]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup minikube
        uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: ${{ matrix.minikube }}
          kubernetes version: ${{ matrix.kubernetes }}
      - name: minikube addon settings
        run: |
          sudo which kubectl
          sudo ls -ltra /usr/bin/kubectl
          sudo ls -la /home/runner/work/_temp
          sudo mv /home/runner/work/_temp/.minikube $HOME
          sudo mv /home/runner/work/_temp/minikube /usr/bin
          sudo chown -R $USER $HOME/.minikube
          sudo ls -ltra /usr/bin/minikube
          sudo minikube addons enable ingress
          sudo minikube addons list
          sudo minikube addons list
